site_name: Networking Course
site_author: Andrea Diamantini

copyright: >
    Andrea Diamantini (c) 2022-2023<br>
    <a href="#__consent">Change Cookie Settings</a>

# -----------------------------------------------------------------------------------------------

theme:
  name: material
  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    font: False
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra:
  consent:
    title: Consenso all'uso dei Cookie(s)
    description: >
      Questo sito memorizza alcuni cookies solo per riconoscere un visitatore 
      che non è alla sua prima visita e alcune preferenze, come il tema di visualizzazione
      della pagina selezionato.<br>
      Se non acconsenti, questa finestra riapparirà ogni volta che riapri il sito.<br>
      Se vuoi cambiare le tue scelte, in fondo alla pagina trovi un link per modificarle ;)
    actions:
     - accept
     - reject

extra_css:
- stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.highlight: {anchor_linenums: True}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}

  
# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  # ---------------------------------------------------------------
  - Teoria:
    - Il Modello OSI:                   teoria/01_OSI.md
    - Implementazioni Reali:            teoria/02_suites.md
    - Gestione e Sviluppo di Internet:  teoria/03_assoc.md
  # ---------------------------------------------------------------    
  - Livello Inferiore:
    - Specifiche IEEE 802:  Inferiore/01_IEEE802.md
    - Tipologie di rete:    Inferiore/02_tipologie.md
    - Topologie di rete:    Inferiore/03_topologie.md
    - Dispositivi di rete:  Inferiore/04_dispositivi.md
    - In Laboratorio:       Inferiore/05_lab.md
   # ---------------------------------------------------------------    
  - Livello Rete:
    - Introduzione:         Rete/00_intro.md
    - Indirizzamento IPv4:  Rete/32_IndirizzamentoIPv4.md
    - (LAB) ipconfig:       Rete/lab_310_ipconfig.md
    - (LAB) ifconfig,ip:    Rete/lab_311_ifconfig_ip.md
    - Subnetting:           Rete/33_subnetting.md
    - IPv4:                 Rete/31_IPv4.md
    - (LAB) ping:           Rete/lab_320_ping.md
    - Routing:              Rete/35_routing.md
    - (LAB) traceroute:     Rete/lab_340_traceroute.md
    - ARP:                  Rete/37_ARP.md
    - (LAB) arp:            Rete/lab_330_arp.md
   # ---------------------------------------------------------------    
  - Livello Trasporto:
    - Introduzione:     Trasporto/00_intro.md
    - Sockets e Porte:  Trasporto/01_sockets_ports.md
    - (LAB) netstat:    Trasporto/lab_410_netstat.md
    - QoS:              Trasporto/02_QoS.md
    - Protocollo TCP:   Trasporto/03_TCP.md
    - Protocollo UDP:   Trasporto/04_UDP.md
    - (LAB) wireshark:  Trasporto/lab_420_wireshark.md
    - (LAB) nmap:       Trasporto/lab_430_nmap.md
    - (LAB) port forwarding: Trasporto/lab_440_port_forwarding.md
  # ---------------------------------------------------------------    
  - Livello Superiore:
    - Introduzione:             Superiore/00_intro.md
    - (LAB) server web:         Superiore/lab_710_server_web.md
    - (LAB) sito web a casa tua:    Superiore/lab_711_sito_casa.md
    - (LAB) Telnet e HTTP:      Superiore/lab_712_telnet_http.md
    - (LAB) DNS clients:        Superiore/lab_720_DNS_clients.md
    - (LAB) DNS server:         Superiore/lab_721_DNS_server.md
    - (LAB) DHCP server:        Superiore/lab_730_DHCP_server.md
    - (LAB) Access Point DIY:   Superiore/lab_731_AccessPoint_DIY.md
    - (LAB) Mail server:        Superiore/lab_740_mail_server.md
    - (LAB) Telnet e LivelloSuperiore: Superiore/lab_741_telnet_mail.md
    
    
