site_name: Networking Course
site_author: Andrea Diamantini

copyright: >
    Andrea Diamantini (c) 2022-2024<br>
    <a href="#__consent">Change Cookie Settings</a><br>
    This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>

# -----------------------------------------------------------------------------------------------

theme:
  name: material
  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    font: False
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra:
  consent:
    title: Consenso all'uso dei Cookie(s)
    description: >
      Questo sito memorizza alcuni cookies solo per riconoscere un visitatore 
      che non è alla sua prima visita e alcune preferenze, come il tema di visualizzazione
      della pagina selezionato.<br>
      Se non acconsenti, questa finestra riapparirà ogni volta che riapri il sito.<br>
      Se vuoi cambiare le tue scelte, in fondo alla pagina trovi un link per modificarle ;)
    actions:
     - accept
     - reject

extra_css:
- stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.highlight: {anchor_linenums: True}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}

  
# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  # ---------------------------------------------------------------
  - Teoria:
    #- Il Modello OSI:                   teoria/00_intro.md
    - la Suite Internet:            teoria/01_suite_internet.md
    - Gestione e Sviluppo di Internet:  teoria/02_assoc.md
    # --

    # --
    # --
    # --
    # --
    # - Livello Superiore: teoria/700_superior.md
  # ---------------------------------------------------------------    
  - Reti:
    - Indirizzamento IPv4:  reti/IndirizzamentoIPv4.md
    - Subnetting:           reti/subnetting.md
    - (PY) ipaddress:       reti/py_ipaddress.md
    - (LAB) ipconfig:       reti/lab_ipconfig.md
    - (LAB) ifconfig,ip:    reti/lab_ifconfig_ip.md
  # ---------------------------------------------------------------    
  - Routing (*):
    - Livello di Rete:      routing/network.md
    - ARP:                  routing/ARP.md
    - NAT:                  routing/NAT.md
    - Routing:              routing/routing.md
    - (LAB) ping:           routing/lab_ping.md
    - (LAB) arp:            routing/lab_arp.md
    - (LAB) traceroute:     routing/lab_traceroute.md
    
  # ---------------------------------------------------------------    
  - Trasporto:
    - Livello di Trasporto:  trasporto/transport.md
    - sockets:               trasporto/py_socket.md
    - (LAB) netstat:         trasporto/lab_netstat.md
    - (LAB) wireshark:       trasporto/lab_wireshark.md
    - (LAB) nmap:            trasporto/lab_nmap.md
    - (LAB) port forwarding: trasporto/lab_port_forwarding.md

  # ---------------------------------------------------------------    
  - HTTP:
    - HTTP:                HTTP/HTTP.md
    - URL:                 HTTP/URL.md
    - Flask:               HTTP/py_Flask.md
    - urllib:              HTTP/py_urllib.md
    - requests:            HTTP/py_requests.md
    - soup:                HTTP/py_bs4.md
    - (LAB) Telnet e HTTP: HTTP/lab_telnet_http.md
    - (LAB) server web:    HTTP/lab_server_web.md
    - (LAB) sito web DIY:  HTTP/lab_sito_casa.md

  # ---------------------------------------------------------------    
  - DNS:
    - DNS:               DNS/DNS.md
    - dnspython:         DNS/py_dnspython.md
    - (LAB) DNS clients: DNS/lab_DNS_clients.md
    - (LAB) DNS server:  DNS/lab_DNS_server.md
    
  # ---------------------------------------------------------------    
  - DHCP:
    - DHCP:                    DHCP/DHCP.md
    - (LAB) DHCP server:       DHCP/lab_DHCP_server.md
    - (LAB) Access Point DIY:  DHCP/lab_AccessPoint_DIY.md
    
  # ---------------------------------------------------------------    
  - MAIL:
    - Posta Elettronica:   MAIL/MAIL.md
    - (PY) smtplib:        MAIL/py_smtplib.md    
    - (LAB) Telnet e Mail: MAIL/lab_telnet_mail.md
    - (LAB) Mail server:   MAIL/lab_mail_server.md
   # ---------------------------------------------------------------    


