site_name: Networking Course
site_author: Andrea Diamantini

copyright: >
    Andrea Diamantini (c) 2022-2023<br>
    <a href="#__consent">Change Cookie Settings</a>

# -----------------------------------------------------------------------------------------------

theme:
  name: material
  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    font: False
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra:
  consent:
    title: Consenso all'uso dei Cookie(s)
    description: >
      Questo sito memorizza alcuni cookies solo per riconoscere un visitatore 
      che non è alla sua prima visita e alcune preferenze, come il tema di visualizzazione
      della pagina selezionato.<br>
      Se non acconsenti, questa finestra riapparirà ogni volta che riapri il sito.<br>
      Se vuoi cambiare le tue scelte, in fondo alla pagina trovi un link per modificarle ;)
    actions:
     - accept
     - reject

extra_css:
- stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.highlight: {anchor_linenums: True}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}

  
# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  - Teoria:
    - Il Modello OSI: teoria/01_OSI.md
    - Implementazioni Reali: teoria/02_suites.md
    - Gestione e Sviluppo di Internet: teoria/03_assoc.md
  - La Suite Internet:
    - Introduzione: InternetSuite/00_intro.md
    - Livello Inferiore: InternetSuite/10_inferiore.md
    - Livello di Rete: InternetSuite/30_network.md
    - Livello di Trasporto: InternetSuite/40_trasporto.md
    - Livello Superiore: InternetSuite/70_superiore.md
  - Protocolli Internet:
    - Introduzione: protocolli/00_intro.md
    - IPv4: protocolli/01_IPv4.md
    - Subnetting: protocolli/02_subnetting.md
  - Laboratorio:
    - Introduzione: laboratorio/00_intro.md
    - "Rete: ipconfig": laboratorio/net_10_ipconfig.md
    - "Rete: ifconfig,ip": laboratorio/net_11_ifconfig_ip.md
    - "Rete: ping": laboratorio/net_20_ping.md
    - "Rete: arp": laboratorio/net_30_arp.md
    - "Rete: traceroute": laboratorio/net_40_traceroute.md
    - "Trasporto: netstat": laboratorio/trasporto_10_netstat.md
    - "Trasporto: wireshark": laboratorio/trasporto_20_wireshark.md
    - "Trasporto: nmap": laboratorio/trasporto_30_nmap.md
    - "Trasporto: port forwarding": laboratorio/trasporto_40_port_forwarding.md
    - "Superiore: server web": laboratorio/sup_10_server_web.md
    - "Superiore: sito web a casa tua": laboratorio/sup_11_sito_casa.md
    - "Superiore: Telnet e HTTP": laboratorio/sup_12_telnet_http.md
    - "Superiore: DNS clients": laboratorio/sup_20_DNS_clients.md
    - "Superiore: DNS server": laboratorio/sup_21_DNS_server.md
    - "Superiore: DHCP server": laboratorio/sup_30_DHCP_server.md
    - "Superiore: Access Point DIY": laboratorio/sup_31_AccessPoint_DIY.md
    - "Superiore: Mail server": laboratorio/sup_40_mail_server.md
    - "Superiore: Telnet e Mail": laboratorio/sup_41_telnet_mail.md
    
