site_name: Networking Course
site_author: Andrea Diamantini

copyright: >
    Andrea Diamantini (c) 2022-2023<br>
    <a href="#__consent">Change Cookie Settings</a>

# -----------------------------------------------------------------------------------------------

theme:
  name: material
  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    font: False
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra:
  consent:
    title: Consenso all'uso dei Cookie(s)
    description: >
      Questo sito memorizza alcuni cookies solo per riconoscere un visitatore 
      che non è alla sua prima visita e alcune preferenze, come il tema di visualizzazione
      della pagina selezionato.<br>
      Se non acconsenti, questa finestra riapparirà ogni volta che riapri il sito.<br>
      Se vuoi cambiare le tue scelte, in fondo alla pagina trovi un link per modificarle ;)
    actions:
     - accept
     - reject

extra_css:
- stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.highlight: {anchor_linenums: True}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}

  
# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  # ---------------------------------------------------------------
  - Teoria:
    - Il Modello OSI:                   teoria/01_OSI.md
    - Implementazioni Reali:            teoria/02_suites.md
    - Gestione e Sviluppo di Internet:  teoria/03_assoc.md
  # ---------------------------------------------------------------    
  - Livello Inferiore:
    - Specifiche IEEE 802:  01_inferiore/01_IEEE802.md
    - Tipologie di rete:    01_inferiore/02_tipologie.md
    - Topologie di rete:    01_inferiore/03_topologie.md
    - Dispositivi di rete:  01_inferiore/04_dispositivi.md
    - In Laboratorio:       01_inferiore/05_lab.md
   # ---------------------------------------------------------------    
  - Livello Rete:
    - Introduzione:         03_rete/00_intro.md
    - Indirizzamento IPv4:  03_rete/32_IndirizzamentoIPv4.md
    - (LAB) ipconfig:       03_rete/lab_310_ipconfig.md
    - (LAB) ifconfig,ip:    03_rete/lab_311_ifconfig_ip.md
    - Subnetting:           03_rete/33_subnetting.md
    - IPv4:                 03_rete/31_IPv4.md
    - (LAB) ping:           03_rete/lab_320_ping.md
    - Routing:              03_rete/35_routing.md
    - (LAB) traceroute:     03_rete/lab_340_traceroute.md
    - ARP:                  03_rete/37_ARP.md
    - (LAB) arp:            03_rete/lab_330_arp.md
   # ---------------------------------------------------------------    
  - Livello Trasporto:
    - Introduzione:          04_trasporto/00_intro.md
    - Sockets e Porte:       04_trasporto/01_sockets_ports.md
    - (LAB) netstat:         04_trasporto/lab_410_netstat.md
    - QoS:                   04_trasporto/02_QoS.md
    - Protocollo TCP:        04_trasporto/03_TCP.md
    - Protocollo UDP:        04_trasporto/04_UDP.md
    - (LAB) wireshark:       04_trasporto/lab_420_wireshark.md
    - (LAB) nmap:            04_trasporto/lab_430_nmap.md
    - (LAB) port forwarding: 04_trasporto/lab_440_port_forwarding.md
  # ---------------------------------------------------------------    
  - Livello Superiore:
    - Introduzione:               07_superiore/00_intro.md
    - Protocollo DNS:             07_superiore/01_DNS.md
    - (LAB) DNS clients:          07_superiore/lab_720_DNS_clients.md
    - (LAB) DNS server:           07_superiore/lab_721_DNS_server.md
    - Protocollo DHCP:            07_superiore/02_DHCP.md
    - (LAB) DHCP server:          07_superiore/lab_730_DHCP_server.md
    - (LAB) Access Point DIY:     07_superiore/lab_731_AccessPoint_DIY.md
    - Protocollo HTTP:            07_superiore/03_HTTP.md
    - (LAB) Telnet e HTTP:        07_superiore/lab_712_telnet_http.md
    - (LAB) server web:           07_superiore/lab_710_server_web.md
    - (LAB) sito web a casa tua:  07_superiore/lab_711_sito_casa.md
    - Posta Elettronica:          07_superiore/04_MAIL.md
    - (LAB) Mail server:          07_superiore/lab_740_mail_server.md
    - (LAB) Telnet e Mail:        07_superiore/lab_741_telnet_mail.md
    
    
