site_name: Networking Course
site_author: Andrea Diamantini
copyright: Andrea Diamantini (c) 2022

# -----------------------------------------------------------------------------------------------

theme:
  name: material
  palette:
    primary: teal
  font:
    text: Roboto
    code: Roboto Mono
  language: it
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
  plugins:
    - search:
        lang: it

extra_css:
- stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - toc: {permalink: True}
  - admonition: {}
  - attr_list: {}
  - def_list: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.superfences: {}
  - pymdownx.emoji: {}
  
# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  - Teoria:
    - Introduzione: teoria/00_intro.md
  - Rete:
    - Introduzione: rete/00_intro.md
  - Trasporto:
    - Introduzione: trasporto/00_intro.md
  - Superiore:
    - Introduzione: superiore/00_intro.md
  - About: about.md


