site_name: Networking Course
site_author: Andrea Diamantini
copyright: Andrea Diamantini (c) 2022

# -----------------------------------------------------------------------------------------------

theme:
  name: material
  palette:
    primary: teal
    accent: green
  font:
    text: Roboto
    code: Roboto Mono
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra_css:
- stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.highlight: {anchor_linenums: True}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}

  
# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  - Teoria:
    - Il Modello OSI: teoria/01_OSI.md
    - Implementazioni Reali: teoria/02_suites.md
    - Gestione e Sviluppo di Internet: teoria/03_assoc.md
  - Rete:
    - Introduzione: rete/00_intro.md
    - IPv4: rete/01_IPv4.md
  - Trasporto:
    - Introduzione: trasporto/00_intro.md
  - Superiore:
    - Introduzione: superiore/00_intro.md
  - About: about.md


