site_name: Networking Course
site_author: Andrea Diamantini

copyright: >
    Andrea Diamantini (c) 2022-2024<br>
    <a href="#__consent">Change Cookie Settings</a><br>
    This work is licensed under <a href="https://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">CC BY-NC-SA 4.0</a>

# -----------------------------------------------------------------------------------------------

theme:
  name: material
  palette:
  # Palette toggle for light mode
  - scheme: default
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    primary: teal
    accent: green
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
    font: False
  language: it
  features:
    - navigation.footer
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.integrate
    - content.code.copy
  plugins:
    - search:
        lang: it

extra:
  consent:
    title: Consenso all'uso dei Cookie(s)
    description: >
      Questo sito memorizza alcuni cookies solo per riconoscere un visitatore 
      che non è alla sua prima visita e alcune preferenze, come il tema di visualizzazione
      della pagina selezionato.<br>
      Se non acconsenti, questa finestra riapparirà ogni volta che riapri il sito.<br>
      Se vuoi cambiare le tue scelte, in fondo alla pagina trovi un link per modificarle ;)
    actions:
     - accept
     - reject

extra_css:
- stylesheets/extra.css

# -----------------------------------------------------------------------------------------------

markdown_extensions:
  - admonition: {}
  - attr_list: {}
  - toc: {}
  - def_list: {}
  - pymdownx.emoji: {}
  - pymdownx.tasklist: {custom_checkbox: True}
  - pymdownx.highlight: {anchor_linenums: True}
  - pymdownx.inlinehilite: {}
  - pymdownx.snippets: {}
  - pymdownx.superfences: {}

  
# -----------------------------------------------------------------------------------------------
 
nav:
  - Home: index.md
  # ---------------------------------------------------------------
  - Teoria:
    #- Il Modello OSI:                   teoria/00_intro.md
    - Implementazioni Reali:            teoria/02_suites.md
    - Gestione e Sviluppo di Internet:  teoria/03_assoc.md
    # --
    - Indirizzamento IPv4:  complementi/01_IndirizzamentoIPv4.md
    - Subnetting:           complementi/02_subnetting.md
    # --
    #- Livello Inferiore:     teoria/100_inferior.md
    # --
    #- Livello di Rete:      teoria/300_network.md
    - ARP (?):                  teoria/302_ARP.md
    #- Routing:              teoria/311_routing.md
    # --
    - Livello di Trasporto: teoria/400_transport.md
    # --
    - Livello Superiore: teoria/700_superior.md
    - DNS:               teoria/701_DNS.md
    - DHCP:              teoria/702_DHCP.md
    - HTTP:              teoria/703_HTTP.md
    - Mail:              teoria/704_MAIL.md
  # ---------------------------------------------------------------    
  - Programmazione:
    - Introduzione:    programmazione/00_intro.md
    - ipaddress:       programmazione/01_ipaddress.md
    - urllib:          programmazione/02_urllib.md
    - requests:        programmazione/03_requests.md
    - Flask:           programmazione/04_Flask.md
    - smtplib:         programmazione/05_smtplib.md
    - dnspython:       programmazione/06_dnspython.md
    - sockets:         programmazione/10_socket.md
    - soup:            programmazione/11_bs4.md
    
   # ---------------------------------------------------------------    
  - Laboratorio:
    - Introduzione:         laboratorio/00_intro.md
    - (LAB) inf:            laboratorio/lab_101_boh.md
    - (LAB) ipconfig:       laboratorio/lab_310_ipconfig.md
    - (LAB) ifconfig,ip:    laboratorio/lab_311_ifconfig_ip.md
    - (LAB) ping:           laboratorio/lab_320_ping.md
    - (LAB) traceroute:     laboratorio/lab_340_traceroute.md
    - (LAB) arp:            laboratorio/lab_330_arp.md
    - (LAB) netstat:        laboratorio/lab_410_netstat.md
    - (LAB) wireshark:      laboratorio/lab_420_wireshark.md
    - (LAB) nmap:           laboratorio/lab_430_nmap.md
    - (LAB) port forwarding: laboratorio/lab_440_port_forwarding.md
    - (LAB) DNS clients:          laboratorio/lab_720_DNS_clients.md
    - (LAB) DNS server:           laboratorio/lab_721_DNS_server.md
    - (LAB) DHCP server:          laboratorio/lab_730_DHCP_server.md
    - (LAB) Access Point DIY:     laboratorio/lab_731_AccessPoint_DIY.md
    - (LAB) Telnet e HTTP:        laboratorio/lab_712_telnet_http.md
    - (LAB) server web:           laboratorio/lab_710_server_web.md
    - (LAB) sito web a casa tua:  laboratorio/lab_711_sito_casa.md
    - (LAB) Mail server:          laboratorio/lab_740_mail_server.md
    - (LAB) Telnet e Mail:        laboratorio/lab_741_telnet_mail.md
   # ---------------------------------------------------------------    
  - Complementi:
    - Introduzione:         complementi/00_intro.md
    - URL:                  complementi/11_URL.md

    
